services:
  - type: web
    name: stress-detection-app
    env: python
    plan: free
    buildCommand: cd stress_project_extended && pip install -r requirements.txt && python manage.py collectstatic --no-input
    startCommand: cd stress_project_extended && python manage.py migrate && gunicorn stress_project.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: stress-detection-app.onrender.com,*.onrender.com
    healthCheckPath: /

